rules:
  # Color

  # Disallow invalid hex colors.
  color-no-invalid-hex: true

  # Font family

  # Disallow duplicate font family names.
  font-family-no-duplicate-names: true
  # Disallow missing generic families in lists of font family names.
  font-family-no-missing-generic-family-keyword: true

  # Function

  # Disallow an invalid expression within calc functions.
  # function-calc-no-invalid: true
  # Disallow an unspaced operator within calc functions.
  # function-calc-no-unspaced-operator: true
  # Disallow direction values in linear-gradient() calls that are not valid according to the standard syntax.
  # function-linear-gradient-no-nonstandard-direction: true

  # String

  # Disallow (unescaped) newlines in strings.
  string-no-newline: true

  # Unit

  # Disallow unknown units.
  unit-no-unknown: true

  # Property

  # Disallow unknown properties.
  property-no-unknown: true

  # Keyframe declaration

  # Disallow !important within keyframe declarations.
  keyframe-declaration-no-important: true

  # Declaration block

  # Disallow duplicate properties within declaration blocks.
  declaration-block-no-duplicate-properties: true
  # Disallow shorthand properties that override related longhand properties.
  declaration-block-no-shorthand-property-overrides: true

  # Block

  # Disallow empty blocks.
  block-no-empty: true

  # Selector

  # Disallow unknown pseudo-class selectors.
  selector-pseudo-class-no-unknown: true
  # Disallow unknown pseudo-element selectors.
  selector-pseudo-element-no-unknown: true
  # Disallow unknown type selectors.
  selector-type-no-unknown: true

  # Media feature

  # Disallow unknown media feature names.
  media-feature-name-no-unknown: true

  # At-rule

  # Disallow unknown at-rules.
  at-rule-no-unknown: []

  # Comment

  # Disallow empty comments.
  comment-no-empty: true

  # General / Sheet

  # Disallow selectors of lower specificity from coming after overriding selectors of higher specificity.
  no-descending-specificity: true
  # Disallow duplicate @import rules within a stylesheet.
  no-duplicate-at-import-rules: true
  # Disallow duplicate selectors within a stylesheet.
  no-duplicate-selectors: true
  # Disallow empty sources.
  no-empty-source: true
  # Disallow extra semicolons (Autofixable).
  no-extra-semicolons: true
  # Disallow double-slash comments (//...) which are not supported by CSS.
  no-invalid-double-slash-comments: true

  # Limit language features
  # Color

  # Require (where possible) or disallow named colors.
  color-named: always-where-possible
  # Disallow hex colors.
  color-no-hex: true

  # Function

  # Specify a blacklist of disallowed functions.
  # function-blacklist: true
  # Disallow scheme-relative urls.
  # function-url-no-scheme-relative: true
  # Specify a blacklist of disallowed URL schemes.
  # function-url-scheme-blacklist: true
  # Specify a whitelist of allowed URL schemes.
  # function-url-scheme-whitelist: true
  # Specify a whitelist of allowed functions.
  # function-whitelist: true

  # Keyframes

  # # Specify a pattern for keyframe names.
  # keyframes-name-pattern: true

  # Number

  # Limit the number of decimal places allowed in numbers.
  number-max-precision: 2

  # Time

  # Specify the minimum number of milliseconds for time values.
  time-min-milliseconds: 15

  # Unit

  # Specify a blacklist of disallowed units.
  unit-blacklist: null
  # Specify a whitelist of allowed units.
  unit-whitelist: null

  # Shorthand property

  # Disallow redundant values in shorthand properties (Autofixable).
  shorthand-property-no-redundant-values: true

  # Value

  # Disallow vendor prefixes for values.
  value-no-vendor-prefix: true

  # Custom property

  # # Specify a pattern for custom properties.
  # custom-property-pattern: true

  # Property

  # # Specify a blacklist of disallowed properties.
  # property-blacklist: true
  # Disallow vendor prefixes for properties.
  property-no-vendor-prefix: true
  # # Specify a whitelist of allowed properties.
  # property-whitelist: true

  # Declaration

  # Disallow longhand properties that can be combined into one shorthand property.
  declaration-block-no-redundant-longhand-properties: true
  # Disallow !important within declarations.
  declaration-no-important: true
  # # Specify a blacklist of disallowed property and unit pairs within declarations.
  # declaration-property-unit-blacklist: true
  # # Specify a whitelist of allowed property and unit pairs within declarations.
  # declaration-property-unit-whitelist: true
  # # Specify a blacklist of disallowed property and value pairs within declarations.
  # declaration-property-value-blacklist: true
  # # Specify a whitelist of allowed property and value pairs within declarations.
  # declaration-property-value-whitelist: true

  # Declaration block

  # Limit the number of declarations within a single-line declaration block.
  declaration-block-single-line-max-declarations: 1

  # Selector

  # # Specify a blacklist of disallowed attribute operators.
  # selector-attribute-operator-blacklist: true
  # # Specify a whitelist of allowed attribute operators.
  # selector-attribute-operator-whitelist: true
  # # Specify a pattern for class selectors.
  # selector-class-pattern: true
  # Specify a blacklist of disallowed combinators.
  selector-combinator-blacklist: []
  # Specify a whitelist of allowed combinators.
  # selector-combinator-whitelist: []
  # Specify a pattern for ID selectors.
  selector-id-pattern: null
  # Limit the number of attribute selectors in a selector.
  selector-max-attribute: null
  # Limit the number of classes in a selector.
  selector-max-class: null
  # Limit the number of combinators in a selector.
  selector-max-combinators: null
  # Limit the number of compound selectors in a selector.
  selector-max-compound-selectors: null
  # Limit the number of adjacent empty lines within selectors.
  selector-max-empty-lines: 0
  # Limit the number of ID selectors in a selector.
  selector-max-id: null
  # Limit the number of pseudo-classes in a selector.
  selector-max-pseudo-class: 1
  # Limit the specificity of selectors.
  selector-max-specificity: null
  # Limit the number of type in a selector.
  selector-max-type: 3
  # Limit the number of universal selectors in a selector.
  selector-max-universal: 0
  # Specify a pattern for the selectors of rules nested within rules.
  selector-nested-pattern: null
  # Disallow qualifying a selector by type.
  selector-no-qualifying-type: null
  # Disallow vendor prefixes for selectors.
  selector-no-vendor-prefix: true
  # # Specify a blacklist of disallowed pseudo-class selectors.
  # selector-pseudo-class-blacklist: []
  # # Specify a whitelist of allowed pseudo-class selectors.
  # selector-pseudo-class-whitelist: []
  # # Specify a blacklist of disallowed pseudo-element selectors.
  # selector-pseudo-element-blacklist: []
  # # Specify a whitelist of allowed pseudo-element selectors.
  # selector-pseudo-element-whitelist: []

  # Media feature

  # # Specify a blacklist of disallowed media feature names.
  # media-feature-name-blacklist: []
  # Disallow vendor prefixes for media feature names.
  media-feature-name-no-vendor-prefix: true
  # # Specify a whitelist of allowed media feature name and value pairs.
  # media-feature-name-value-whitelist: true
  # # Specify a whitelist of allowed media feature names.
  # media-feature-name-whitelist: true

  # Custom media

  # # Specify a pattern for custom media query names.
  # custom-media-pattern: true

  # At-rule

  # Specify a blacklist of disallowed at-rules.
  at-rule-blacklist: []
  # Disallow vendor prefixes for at-rules.
  at-rule-no-vendor-prefix: true
  # Specify a requirelist of properties for an at-rule.
  at-rule-property-requirelist:
    - at-rule-name: []

  # Specify a whitelist of allowed at-rules.
  at-rule-whitelist: []

  # Comment

  # # Specify a blacklist of disallowed words within comments.
  # comment-word-blacklist: []

  # General / Sheet

  # Limit the depth of nesting.
  max-nesting-depth: null
  # Disallow unknown animations.
  no-unknown-animations: true

  # Stylistic issues
  # Color

  # Specify lowercase or uppercase for hex colors (Autofixable).
  color-hex-case: lower
  # # Specify short or long notation for hex colors (Autofixable).
  # color-hex-length: true

  # Font family

  # Specify whether or not quotation marks should be used around font family names.
  font-family-name-quotes: always-unless-keyword

  # Font weight

  # Require numeric or named (where possible) font-weight values. Also, when named values are expected, require only valid names.
  font-weight-notation: named-where-possible

  # Function

  # Require a newline or disallow whitespace after the commas of functions (Autofixable).
  # function-comma-newline-after: always-multi-line
  # # Require a newline or disallow whitespace before the commas of functions (Autofixable).
  # function-comma-newline-before: never
  # # Require a single space or disallow whitespace after the commas of functions (Autofixable).
  # function-comma-space-after: true
  # # Require a single space or disallow whitespace before the commas of functions (Autofixable).
  # function-comma-space-before: true
  # # Limit the number of adjacent empty lines within functions (Autofixable).
  # function-max-empty-lines: 0
  # # Specify lowercase or uppercase for function names (Autofixable).
  # function-name-case: lower
  # # Require a newline or disallow whitespace on the inside of the parentheses of functions (Autofixable).
  # function-parentheses-newline-inside: true
  # # Require a single space or disallow whitespace on the inside of the parentheses of functions (Autofixable).
  # function-parentheses-space-inside: true
  # # Require or disallow quotes for urls.
  # function-url-quotes: true
  # # Require or disallow whitespace after functions (Autofixable).
  # function-whitespace-after: true

  # Number

  # Require or disallow a leading zero for fractional numbers less than 1 (Autofixable).
  number-leading-zero: always
  # Disallow trailing zeros in numbers (Autofixable).
  number-no-trailing-zeros: true

  # String

  # Specify single or double quotes around strings (Autofixable).
  string-quotes: double

  # Length

  # Disallow units for zero lengths (Autofixable).
  length-zero-no-unit: true

  # Unit

  # Specify lowercase or uppercase for units (Autofixable).
  unit-case: lower

  # Value

  # Specify lowercase or uppercase for keywords values (Autofixable).
  value-keyword-case: lower

  # Value list

  # Require a newline or disallow whitespace after the commas of value lists (Autofixable).
  value-list-comma-newline-after: always-multi-line
  # Require a newline or disallow whitespace before the commas of value lists.
  value-list-comma-newline-before: never-multi-line
  # Require a single space or disallow whitespace after the commas of value lists (Autofixable).
  value-list-comma-space-after: always
  # Require a single space or disallow whitespace before the commas of value lists (Autofixable).
  value-list-comma-space-before: never
  # Limit the number of adjacent empty lines within value lists (Autofixable).
  value-list-max-empty-lines: 0

  # Custom property

  # Require or disallow an empty line before custom properties (Autofixable).
  custom-property-empty-line-before: [never]

  # Property

  # Specify lowercase or uppercase for properties (Autofixable).
  property-case: lower

  # Declaration

  # Require a single space or disallow whitespace after the bang of declarations (Autofixable).
  # declaration-bang-space-after: true
  # Require a single space or disallow whitespace before the bang of declarations (Autofixable).
  # declaration-bang-space-before: true
  # Require a newline or disallow whitespace after the colon of declarations (Autofixable).
  # declaration-colon-newline-after: true
  # Require a single space or disallow whitespace after the colon of declarations (Autofixable).
  # declaration-colon-space-after: true
  # Require a single space or disallow whitespace before the colon of declarations (Autofixable).
  # declaration-colon-space-before: true
  # Require or disallow an empty line before declarations (Autofixable).
  # declaration-empty-line-before: true

  # Declaration block

  # Require a newline or disallow whitespace after the semicolons of declaration blocks (Autofixable).
  # declaration-block-semicolon-newline-after: true
  # # Require a newline or disallow whitespace before the semicolons of declaration blocks.
  # declaration-block-semicolon-newline-before: true
  # # Require a single space or disallow whitespace after the semicolons of declaration blocks (Autofixable).
  # declaration-block-semicolon-space-after: true
  # # Require a single space or disallow whitespace before the semicolons of declaration blocks (Autofixable).
  # declaration-block-semicolon-space-before: true
  # # Require or disallow a trailing semicolon within declaration blocks (Autofixable).
  # declaration-block-trailing-semicolon: true

  # Block

  # Require a newline after the opening brace of blocks (Autofixable).
  block-opening-brace-newline-after: always
  # Require a newline or disallow whitespace before the opening brace of blocks (Autofixable).
  block-opening-brace-newline-before: never
  # Require a single space or disallow whitespace after the opening brace of blocks (Autofixable).
  block-opening-brace-space-after: null
  # Require a single space or disallow whitespace before the opening brace of blocks (Autofixable).
  block-opening-brace-space-before: always
  # Require or disallow an empty line before the closing brace of blocks (Autofixable).
  block-closing-brace-empty-line-before: never
  # Require a newline or disallow whitespace after the closing brace of blocks (Autofixable).
  block-closing-brace-newline-after: always
  # Require a newline or disallow whitespace before the closing brace of blocks (Autofixable).
  block-closing-brace-newline-before: always
  # Require a single space or disallow whitespace after the closing brace of blocks.
  block-closing-brace-space-after: null
  # Require a single space or disallow whitespace before the closing brace of blocks (Autofixable).
  block-closing-brace-space-before: null

  # Selector

  # # Require a single space or disallow whitespace on the inside of the brackets within attribute selectors (Autofixable).
  # selector-attribute-brackets-space-inside: true
  # # Require a single space or disallow whitespace after operators within attribute selectors (Autofixable).
  # selector-attribute-operator-space-after: true
  # # Require a single space or disallow whitespace before operators within attribute selectors (Autofixable).
  # selector-attribute-operator-space-before: true
  # # Require or disallow quotes for attribute values.
  # selector-attribute-quotes: true
  # Require a single space or disallow whitespace after the combinators of selectors (Autofixable).
  # selector-combinator-space-after: true
  # Require a single space or disallow whitespace before the combinators of selectors (Autofixable).
  # selector-combinator-space-before: true
  # Disallow non-space characters for descendant combinators of selectors (Autofixable).
  selector-descendant-combinator-no-non-space: true
  # Specify lowercase or uppercase for pseudo-class selectors (Autofixable).
  selector-pseudo-class-case: lower
  # Require a single space or disallow whitespace on the inside of the parentheses within pseudo-class selectors (Autofixable).
  selector-pseudo-class-parentheses-space-inside: never
  # Specify lowercase or uppercase for pseudo-element selectors.
  selector-pseudo-element-case: lower
  # Specify single or double colon notation for applicable pseudo-elements (Autofixable).
  selector-pseudo-element-colon-notation: double
  # Specify lowercase or uppercase for type selectors (Autofixable).
  selector-type-case: lower

  # Selector list

  # Require a newline or disallow whitespace after the commas of selector lists (Autofixable).
  selector-list-comma-newline-after: always-multi-line
  # Require a newline or disallow whitespace before the commas of selector lists (Autofixable).
  selector-list-comma-newline-before: never-multi-line
  # Require a single space or disallow whitespace after the commas of selector lists (Autofixable).
  selector-list-comma-space-after: always-single-line
  # Require a single space or disallow whitespace before the commas of selector lists (Autofixable).
  selector-list-comma-space-before: never

  # Rule

  # # Require or disallow an empty line before rules (Autofixable).
  # rule-empty-line-before: true

  # Media feature

  # Require a single space or disallow whitespace after the colon in media features (Autofixable).
  # media-feature-colon-space-after: true
  # # Require a single space or disallow whitespace before the colon in media features (Autofixable).
  # media-feature-colon-space-before: true
  # # Specify lowercase or uppercase for media feature names (Autofixable).
  # media-feature-name-case: lower
  # # Require a single space or disallow whitespace on the inside of the parentheses within media features (Autofixable).
  # media-feature-parentheses-space-inside: true
  # # Require a single space or disallow whitespace after the range operator in media features (Autofixable).
  # media-feature-range-operator-space-after: true
  # # Require a single space or disallow whitespace before the range operator in media features (Autofixable).
  # media-feature-range-operator-space-before: true

  # # Media query list

  # # Require a newline or disallow whitespace after the commas of media query lists (Autofixable).
  # media-query-list-comma-newline-after: true
  # # Require a newline or disallow whitespace before the commas of media query lists.
  # media-query-list-comma-newline-before: true
  # # Require a single space or disallow whitespace after the commas of media query lists (Autofixable).
  # media-query-list-comma-space-after: true
  # # Require a single space or disallow whitespace before the commas of media query lists (Autofixable).
  # media-query-list-comma-space-before: true

  # At-rule

  # # Require or disallow an empty line before at-rules (Autofixable).
  # at-rule-empty-line-before: [always]
  # # Specify lowercase or uppercase for at-rules names (Autofixable).
  # at-rule-name-case: lower
  # # Require a newline after at-rule names.
  # at-rule-name-newline-after: always
  # # Require a single space after at-rule names (Autofixable).
  # at-rule-name-space-after: always-single-line
  # # Require a newline after the semicolon of at-rules (Autofixable).
  # at-rule-semicolon-newline-after: always
  # # Require a single space or disallow whitespace before the semicolons of at-rules.
  # at-rule-semicolon-space-before: never

  # Comment

  # Require or disallow an empty line before comments (Autofixable).
  comment-empty-line-before: always
  # Require or disallow whitespace on the inside of comment markers (Autofixable).
  comment-whitespace-inside: never

  # General / Sheet

  # Specify indentation (Autofixable).
  indentation: tab
  # Specify unix or windows linebreaks (Autofixable).
  linebreaks: unix
  # Limit the number of adjacent empty lines.
  max-empty-lines: 1
  # Limit the length of a line.
  max-line-length: 60
  # Disallow end-of-line whitespace (Autofixable).
  no-eol-whitespace: true
  # Disallow missing end-of-source newlines (Autofixable).
  no-missing-end-of-source-newline: true
  # Disallow empty first lines (Autofixable).
  no-empty-first-line: true
